GitHub actions deploy example to gh pages
devcows/hugo-universal-theme pull request #297
Opened 2021-07-23 06:20 UTC by chepo92

Adds action to build example git github actions to ease the start of new site from the example

2021-07-23 07:37 UTC, ryanfox1985 requested changes

2021-07-23 07:37 UTC, ryanfox1985 commented on .github/workflows/main.yml
> +      - main  # Set a branch to deploy
could you replace for master?

2021-07-23 07:37 UTC, ryanfox1985 commented on .github/workflows/main.yml
> +    runs-on: ubuntu-18.04
perhaps use 20.X LTS?

2021-07-23 07:37 UTC, ryanfox1985 commented on .github/workflows/main.yml
> +          publish_dir: ./exampleSite/public  # defaults to ./public # directorio source para hacer el deploy (debe coincidir con lo configurado para hacer el build en config.toml), eg hace el Deploy
could you translate this spanish text to english?

2021-07-26 07:16 UTC, ryanfox1985 approved these changes

2021-07-26 07:17 UTC, merged

2021-07-31 04:19 UTC, chepo92 commented
@ryanfox1985  can you run the deploy again? IDK why it failed, it worked ok in my fork, maybe is it blocked to push to gh-pages. 

```
  /usr/bin/git push origin gh-pages
  remote: fatal error in commit_refs        
  To https://github.com/devcows/hugo-universal-theme.git
   ! [remote rejected] gh-pages -> gh-pages (failure)
  error: failed to push some refs to 'https://github.com/devcows/hugo-universal-theme.git'
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```

2021-07-31 09:19 UTC, ryanfox1985 commented
Hello @chepo92, thanks for the feedback, I noticed too. I think is a matter of repository configuration. I'll take a look.

2021-07-31 09:22 UTC, ryanfox1985 commented
![image](https://user-images.githubusercontent.com/1152728/127735400-b539fe4d-3bec-4c60-93c9-6ef69ded2650.png)

2021-07-31 09:30 UTC, ryanfox1985 commented
I found the issue, I created manually the gh-pages branch and I rerun the flow https://github.com/devcows/hugo-universal-theme/runs/3208399294.

2021-07-31 15:18 UTC, chepo92 commented
Nice, now you also may want to add the url to the sidebar/description of the repo

2021-07-31 15:38 UTC, ryanfox1985 commented
@chepo92 I added to the description https://github.com/devcows/hugo-universal-theme#universal-theme-for-hugo . Do you mean this right?

2021-07-31 15:52 UTC, chepo92 commented
I mean this, you may also add the tag/topics (eg "hugo" "template") to make it easier to find this repo: 
![ss](https://user-images.githubusercontent.com/26207806/127745357-c33c088f-0343-43b8-a2a8-c7b9c787b4ad.png)

2021-07-31 15:58 UTC, ryanfox1985 commented
nice catch, I updated. Thanks!