Use hide_summary also for blogs list
devcows/hugo-universal-theme pull request #356
Opened 2022-05-04 09:01 UTC by g0hl1n

Apply the `recent_posts.hide_summary` flag introduced in https://github.com/devcows/hugo-universal-theme/pull/283 also to the default blog list.

Signed-off-by: Richard Leitner <dev@bubus.at>

2022-05-04 09:22 UTC, ryanfox1985 requested changes
could you hide the read-more too? just to be coherent with the other hide summary.

https://github.com/devcows/hugo-universal-theme/blob/f51ed131b9ee83b7b383e4ffecbe220d0f664518/layouts/partials/recent_posts.html#L52-L57

2022-05-04 11:00 UTC, g0hl1n commented
ACK. I've updated the branch accordingly.

2022-05-04 14:09 UTC, ryanfox1985 commented
changes looks good, please could you change the doc as well? 

https://github.com/devcows/hugo-universal-theme#recent-posts

could you add a mention that `.hide_summary` also affects to blog page too?

2022-05-05 04:20 UTC, g0hl1n commented
I've added an additional sentence as documentation for this. Thanks for the catch. I totally forgot about the documentation.

2022-05-05 07:44 UTC, ryanfox1985 approved these changes

2022-05-05 07:44 UTC, merged